kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: osb-frontend
  namespace: 
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'e2e-metadata-frontend:latest'
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: '2'
      memory: 2Gi
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/ludovic-pl/OSB-openshift.git'
    contextDir: /studybuilder
  mountTrustedCA: true
