kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: api-route-swagger
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    openshift.io/host.generated: 'true'
spec:
  path: /api
  to:
    kind: Service
    name: api-swagger
    weight: 100
  port:
    targetPort: 5003
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None