apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: ALLOW_ORIGIN_REGEX
              value: .*
            - name: MS_GRAPH_GROUPS_QUERY
            - name: MS_GRAPH_INTEGRATION_ENABLED
            - name: OAUTH_API_APP_ID
            - name: OAUTH_API_APP_SECRET
            - name: OAUTH_APP_ID
            - name: OAUTH_APP_SECRET
            - name: OAUTH_CLIENT_ID
            - name: OAUTH_ENABLED
              value: "False"
            - name: OAUTH_METADATA_URL
            - name: OAUTH_RBAC_ENABLED
              value: "False"
            - name: OAUTH_SWAGGER_APP_ID
            - name: OIDC_METADATA_DOCUMENT
            - name: UVICORN_PORT
              value: "5003"
            - name: UVICORN_ROOT_PATH
              value: /api
            - name: neo4jpwd
              valueFrom:
                secretKeyRef:
                  name: neo4j-pwd
                  key: NEO4J_MDR_AUTH_PASSWORD
            - name: NEO4J_MDR_BOLT_PORT
              value: '7687'
            - name: NEO4J_MDR_HOST
              value: database.climber-scale-24121953.svc.cluster.local
            - name: NEO4J_MDR_AUTH_USER
              value: neo4j
            - name: NEO4J_MDR_AUTH_PASSWORD
              value: $(neo4jpwd)
            - name: NEO4J_DSN
              value: bolt://$(NEO4J_MDR_AUTH_USER):$(NEO4J_MDR_AUTH_PASSWORD)@$(NEO4J_MDR_HOST):$(NEO4J_MDR_BOLT_PORT)/mdrdb
          image: e2e-metadata-api
          name: api
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            limits:
              cpu: '500m'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 1Gi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: consumerapi
  name: consumerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumerapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: consumerapi
    spec:
      containers:
        - env:
            - name: ALLOW_ORIGIN_REGEX
              value: .*
            - name: OAUTH_API_APP_ID
            - name: OAUTH_ENABLED
              value: "False"
            - name: OAUTH_METADATA_URL
            - name: OAUTH_RBAC_ENABLED
              value: "False"
            - name: OAUTH_SWAGGER_APP_ID
            - name: UVICORN_APP
              value: consumer_api.consumer_api:app
            - name: UVICORN_PORT
              value: "5008"
            - name: UVICORN_ROOT_PATH
              value: /consumer-api
            - name: neo4jpwd
              valueFrom:
                secretKeyRef:
                  name: neo4j-pwd
                  key: NEO4J_MDR_AUTH_PASSWORD
            - name: NEO4J_MDR_BOLT_PORT
              value: '7687'
            - name: NEO4J_MDR_HOST
              value: database.climber-scale-24121953.svc.cluster.local
            - name: NEO4J_MDR_AUTH_USER
              value: neo4j
            - name: NEO4J_MDR_AUTH_PASSWORD
              value: $(neo4jpwd)
            - name: NEO4J_DSN
              value: bolt://$(NEO4J_MDR_AUTH_USER):$(NEO4J_MDR_AUTH_PASSWORD)@$(NEO4J_MDR_HOST):$(NEO4J_MDR_BOLT_PORT)/mdrdb
          image: e2e-metadata-api
          name: consumerapi
          resources:
            limits:
              cpu: '500m'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 1Gi
      restartPolicy: Always