apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: consumerapi
  name: consumerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumerapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: consumerapi
    spec:
      containers:
        - env:
            - name: ALLOW_ORIGIN_REGEX
              value: .*
            - name: NEO4J_DSN
              value: bolt://neo4j:changeme1234@database:7687/mdrdb
            - name: OAUTH_API_APP_ID
            - name: OAUTH_ENABLED
              value: "False"
            - name: OAUTH_METADATA_URL
            - name: OAUTH_RBAC_ENABLED
              value: "False"
            - name: OAUTH_SWAGGER_APP_ID
            - name: UVICORN_APP
              value: consumer_api.consumer_api:app
            - name: UVICORN_PORT
              value: "5008"
            - name: UVICORN_ROOT_PATH
              value: /consumer-api
          image: e2e-metadata-api
          name: consumerapi
      restartPolicy: Always
