apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 7687
    - name: "5001"
      port: 5001
      targetPort: 7474
  selector:
    io.kompose.service: database
