apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: API_BASE_URL
              value: http://api:5003
            - name: DOC_BASE_URL
              value: http://documentation
            - name: NEODASH_BASE_URL
              value: http://neodash:5007
            - name: OAUTH_API_APP_ID
            - name: OAUTH_ENABLED
              value: "false"
            - name: OAUTH_METADATA_URL
            - name: OAUTH_UI_APP_ID
          image: e2e-metadata-frontend
          name: frontend
          ports:
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
