apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: data
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: ALLOW_ORIGIN_REGEX
              value: .*
            - name: MS_GRAPH_GROUPS_QUERY
            - name: MS_GRAPH_INTEGRATION_ENABLED
            - name: NEO4J_DSN
              value: bolt://neo4j:changeme1234@database:7687/mdrdb
            - name: OAUTH_API_APP_ID
            - name: OAUTH_API_APP_SECRET
            - name: OAUTH_APP_ID
            - name: OAUTH_APP_SECRET
            - name: OAUTH_CLIENT_ID
            - name: OAUTH_ENABLED
              value: "False"
            - name: OAUTH_METADATA_URL
            - name: OAUTH_RBAC_ENABLED
              value: "False"
            - name: OAUTH_SWAGGER_APP_ID
            - name: OIDC_METADATA_DOCUMENT
            - name: UVICORN_PORT
              value: "5003"
            - name: UVICORN_ROOT_PATH
              value: /api
          image: e2e-metadata-api
          name: api
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: consumerapi
  name: consumerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumerapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: consumerapi
    spec:
      containers:
        - env:
            - name: ALLOW_ORIGIN_REGEX
              value: .*
            - name: NEO4J_DSN
              value: bolt://neo4j:changeme1234@database:7687/mdrdb
            - name: OAUTH_API_APP_ID
            - name: OAUTH_ENABLED
              value: "False"
            - name: OAUTH_METADATA_URL
            - name: OAUTH_RBAC_ENABLED
              value: "False"
            - name: OAUTH_SWAGGER_APP_ID
            - name: UVICORN_APP
              value: consumer_api.consumer_api:app
            - name: UVICORN_PORT
              value: "5008"
            - name: UVICORN_ROOT_PATH
              value: /consumer-api
          image: e2e-metadata-api
          name: consumerapi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_server_bolt_advertised__address
              value: localhost:5002
            - name: NEO4J_server_default__advertised__address
              value: localhost
            - name: NEO4J_server_default__listen__address
              value: 0.0.0.0
            - name: NEO4J_server_http_advertised__address
              value: localhost:5001
            - name: NEO4J_server_memory_heap_initial__size
              value: 2G
            - name: NEO4J_server_memory_heap_max__size
              value: 2G
            - name: NEO4J_server_memory_pagecache_size
              value: 1G
          image: e2e-metadata-db
          name: database
          resources:
            limits:
              cpu: '4'
              memory: 12Gi
            requests:
              cpu: '2'
              memory: 8Gi
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: documentation
  name: documentation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: documentation
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: documentation
    spec:
      containers:
        - image: e2e-metadata-doc
          name: documentation
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: API_BASE_URL
              value: http://api:5003
            - name: DOC_BASE_URL
              value: http://documentation
            - name: NEODASH_BASE_URL
              value: http://neodash:5007
            - name: OAUTH_API_APP_ID
            - name: OAUTH_ENABLED
              value: "false"
            - name: OAUTH_METADATA_URL
            - name: OAUTH_UI_APP_ID
          image: e2e-metadata-frontend
          name: frontend
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 2Gi
          ports:
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: neodash
  name: neodash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neodash
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o helm/
        kompose.version: 1.35.0 (HEAD)
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: neodash
    spec:
      containers:
        - env:
            - name: NGINX_PORT
              value: "5007"
            - name: ssoDiscoveryUrl
              value: https://localhost.com
            - name: ssoEnabled
              value: "false"
            - name: standalone
              value: "true"
            - name: standaloneAllowLoad
              value: "true"
            - name: standaloneDashboardDatabase
              value: mdrdb
            - name: standaloneDashboardName
              value: Activity Library Dashboard
            - name: standaloneDatabase
              value: mdrdb
            - name: standaloneHost
              value: localhost
            - name: standalonePassword
              value: changeme1234
            - name: standalonePort
              value: "5002"
            - name: standaloneProtocol
              value: neo4j
            - name: standaloneUsername
              value: neo4j
          image: e2e-metadata-neodash
          name: neodash
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 2Gi
          ports:
            - containerPort: 5007
              protocol: TCP
      restartPolicy: Always
---apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 7687
    - name: "5001"
      port: 5001
      targetPort: 7474
  selector:
    io.kompose.service: database
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: neodash
  name: neodash
spec:
  ports:
    - name: "5007"
      port: 5007
      targetPort: 5007
  selector:
    io.kompose.service: neodash
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    io.kompose.service: frontend
